apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hello-world-logs-pvc
  namespace: hello-world
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: "20Gi"
  storageClassName: alicloud-disk-ssd
