apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: hello-world
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/PFS-Mohamed/hello_world
    targetRevision: main
    path: k8s/apps/hello-world
  destination:
    server: https://kubernetes.default.svc
    namespace: pfs-builder
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      